### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by mkeroppi** [MatrixDJ96/EZBlocker2#9] opened 2018-03-21 02:47 UTC
EZBlocker 2 sometimes has high cpu usage now (10-20% on my system).  It seems to be using an increasing amount of cpu as it runs (even without playing any music in Spotify).

**Comment by MatrixDJ96** [comment] 2018-03-21 13:32
It's strange because in my pc the cpu is not used by ezblocker
![immagine](https://user-images.githubusercontent.com/8330294/37712614-afa6d4d6-2d14-11e8-8bf0-07625ee37ba6.png)

**Comment by mkeroppi** [comment] 2018-03-21 19:11
Not sure if it will help, but I will get a screenshot the next time it happens.

It has not happened yet after a restart, but it was the only program doing it.

**Comment by cy2k** [comment] 2018-03-22 02:45
Just happened to me tonight, wasn't even using Spotify at the time.  Had to close it.  I'll follow up if it happens again.

**Comment by MatrixDJ96** [comment] 2018-03-22 15:50
I think that the problem is related to memory usage:
![immagine](https://user-images.githubusercontent.com/8330294/37781415-f37edf78-2df0-11e8-860e-e3ebbef8fde8.png)

Commit e671b84 should have fixed this problemCheck

**Comment by MatrixDJ96** [comment] 2018-03-23 08:20
Fixed

**Closed by MatrixDJ96** 2018-03-23 08:20 UTC
